// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProject(arg1:string,arg2:string):Promise<main.Project>;

export function GetProjects():Promise<Array<main.Project>>;

export function GetSettings():Promise<main.Settings>;

export function RemoveProject(arg1:string):Promise<void>;

export function RunTinker(arg1:string,arg2:string):Promise<string>;

export function RunTinkerStreaming(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function UpdateSettings(arg1:main.Settings):Promise<void>;
